// src/src/app/shared/layout/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { faHammer, faWallet, faCode, faKey, faLink } from '@fortawesome/free-solid-svg-icons';
import { Action } from '../../actions/action';
import { Actions } from '../../actions/actions';
import { Module } from '../../model/module';
import { DataService } from '../../services/data.service';

@Component({
  selector: 'w3tk-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent implements OnInit {

  faWallet = faWallet;
  faHammer = faHammer;
  faCode = faCode;
  faKey = faKey;
  faLink = faLink;

  actions: Action[] = Actions.get();
  modules = [
    { module: Module.KeyManagement, icon: faKey},
    { module: Module.Wallet,        icon: faWallet},
    { module: Module.Blockchain,    icon: faLink},
    { module: Module.Utils,         icon: faCode}
  ]

  getKeyMgmt() { return this.getActions(Module.KeyManagement); }
  getWallet() { return this.getActions(Module.Wallet); }
  getUtils() { return this.getActions(Module.Utils); }

  getActions(mod: Module) {
    return this.actions.filter(x => x.module == mod);
  }
  
  constructor(public dataService: DataService) { }

  ngOnInit(): void {
  }

  addAction(action: Action) {
    this.dataService.addAction(action);
  }

}

<div class="px-3 pt-3 text-white h-100 d-flex flex-column">
  <div class="align-items-center">
    <a href="#" class="p-2 text-white text-decoration-none">
      <img src="assets/img/favicon.png" class="px-2" style="height: 20px;" /> <span class="p-3" style="font-size: large; vertical-align: -0.25rem;">Web3ToolKit</span>
    </a>
  </div>
    <hr>

    <div class="accordion flex-grow-1" id="menuAccordion" style="overflow-y: auto;">
      <div class="accordion-item">
        <h2 class="accordion-header" id="acc-headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#acc-collapseOne" aria-expanded="true" aria-controls="acc-collapseOne">
            <fa-icon [icon]="faKey" class="px-2"></fa-icon> Key Management
          </button>
        </h2>
        <div id="acc-collapseOne" class="accordion-collapse collapse show" aria-labelledby="acc-headingOne">
          <div *ngFor="let action of getKeyMgmt()" class="accordion-body">
            <a href="#" (click)="addAction(action)" class="nav-link">{{action.title}} <img *ngIf="action.requiresConnection" src="assets/img/circle.svg" class="p-2" title="This action requires an active internet connection." style="float: right;"></a> 
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="acc-headingTwo">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#acc-collapseTwo" aria-expanded="true" aria-controls="acc-collapseTwo">
            <fa-icon [icon]="faWallet" class="px-2"></fa-icon> Wallet
          </button>
        </h2>
        <div id="acc-collapseTwo" class="accordion-collapse collapse show" aria-labelledby="acc-headingTwo">
          <div *ngFor="let action of getWallet()" class="accordion-body">
            <a href="#" (click)="addAction(action)" class="nav-link">{{action.title}} <img *ngIf="action.requiresConnection" src="assets/img/circle.svg" class="p-2" title="This action requires an active internet connection." style="float: right;"></a> 
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="acc-headingThree">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#acc-collapseThree" aria-expanded="true" aria-controls="acc-collapseThree">
            <fa-icon [icon]="faCode" class="px-2"></fa-icon> Utils
          </button>
        </h2>
        <div id="acc-collapseThree" class="accordion-collapse collapse show" aria-labelledby="acc-headingThree">
          <div *ngFor="let action of getUtils()" class="accordion-body">
            <a href="#" (click)="addAction(action)" class="nav-link">{{action.title}} <img *ngIf="action.requiresConnection" src="assets/img/circle.svg" class="p-2" title="This action requires an active internet connection." style="float: right;"></a> 
          </div>
        </div>
      </div>
    </div>
    
  <div class="mb-3" style="position: relative; bottom: 0px;">
    <hr>
    <a href="#" class="mx-3 text-white text-decoration-none" [routerLink]="['/about']" >About</a>
  </div>

</div>

// src/components/layout/Sidebar.tsx
'use client';

import { Wallet, Code, Key, Link2, type LucideIcon } from 'lucide-react';
import { Action } from '@/lib/actions/action';
import { Actions } from '@/lib/actions/actions';
import { Module } from '@/lib/models/module';
import { useAppStore } from '@/lib/store';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

const modules: { module: Module; icon: LucideIcon }[] = [
  { module: Module.KeyManagement, icon: Key },
  { module: Module.Wallet, icon: Wallet },
  { module: Module.Blockchain, icon: Link2 },
  { module: Module.Utils, icon: Code },
];

export function Sidebar() {
  const addAction = useAppStore((s) => s.addAction);
  const actions: Action[] = Actions.get();

  const getActions = (mod: Module) => actions.filter((x) => x.module === mod);

  const handleAddAction = (action: Action) => {
    addAction(action);
  };

  return (
    <div className="px-3 pt-3 text-foreground h-full flex flex-col">
      <div className="whitespace-nowrap text-center">Operations</div>
      <hr className="border-border my-2" />
      <Accordion type="multiple" defaultValue={modules.map((m) => m.module)} className="grow overflow-y-auto">
        {modules.map((mod) => (
          <AccordionItem key={mod.module} value={mod.module}>
            <AccordionTrigger className="py-1 text-sm">
              <span className="flex items-center gap-2">
                <mod.icon className="h-4 w-4" /> {mod.module}
              </span>
            </AccordionTrigger>
            <AccordionContent>
              {getActions(mod.module).map((action) => (
                <button
                  key={action.id}
                  onClick={() => handleAddAction(action)}
                  className="block w-full text-left py-1 pl-6 text-sm text-foreground hover:text-accent cursor-pointer bg-transparent border-0"
                  title={action.description}
                >
                  {action.title}
                  {action.requiresConnection && (
                    <img src="/img/circle.svg" className="p-2 float-right" title="This action requires an active internet connection." alt="requires connection" />
                  )}
                </button>
              ))}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
}
