// src/components/ActionsInUse.tsx
'use client';

import { Play, Trash2 } from 'lucide-react';
import { useAppStore } from '@/lib/store';
import { ActionCard } from './layout/ActionCard';
import { Action } from '@/lib/actions/action';
import { Card, CardHeader } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

export function ActionsInUse() {
  const actions = useAppStore((s) => s.actions);
  const getInput = useAppStore((s) => s.getInput);
  const addResult = useAppStore((s) => s.addResult);

  const play = async () => {
    for (const action of actions) {
      await executeAction(action);
    }
  };

  const executeAction = (action: Action): Promise<void> => {
    return new Promise(async (resolve) => {
      setTimeout(async () => {
        try {
          const result = await action.run(getInput());
          addResult(action.title, result);
        } catch (error) {
          addResult(action.title, String(error));
        }
        resolve();
      });
    });
  };

  const clear = () => {
    useAppStore.setState({ actions: [] });
  };

  return (
    <>
      <Card className="mb-1 bg-primary/10">
        <CardHeader className="flex flex-row items-center justify-between py-2 px-3 font-bold">
          <div>Actions</div>
          <div className="flex gap-1">
            <Button variant="ghost" size="icon" onClick={clear} className="h-7 w-7">
              <Trash2 className="h-4 w-4" />
            </Button>
            <Button variant="ghost" size="icon" onClick={play} className="h-7 w-7 text-green-500">
              <Play className="h-4 w-4" />
            </Button>
          </div>
        </CardHeader>
      </Card>
      <div>
        {actions.map((action) => (
          <ActionCard key={action.id} action={action} />
        ))}
      </div>
    </>
  );
}

// src/src/app/actions-inuse/actions-inuse.component.ts
import { Component, OnInit } from '@angular/core';
import { faPlay, faTrash } from '@fortawesome/free-solid-svg-icons';
import { Action } from '../shared/actions/action';
import { DataService } from '../shared/services/data.service';

@Component({
  selector: 'w3tk-actions-inuse',
  templateUrl: './actions-inuse.component.html',
  styleUrls: ['./actions-inuse.component.scss']
})
export class ActionsInuseComponent implements OnInit {
  faPlay = faPlay;
  faTrash = faTrash;

  constructor(public dataService: DataService) { 
  }

  ngOnInit(): void {
  }

  async play() {
    for (var action of this.dataService.actions) {
      await this.executeAction(action);
    }
  }

  private executeAction(action: Action): Promise<void> {
    return new Promise(async (resolve) => {
      setTimeout(async () => {
        try {
          let result = await action.run(this.dataService.getInput());
          this.dataService.addResult(action.title, result);
        } catch (error) {
          this.dataService.addResult(action.title, String(error));
        }
        resolve();
      });
    });
  }

  clear() {
    this.dataService.actions = [];
  }

}

<!-- <w3tk-action title='My Action' (onClick)="myAction()">
    <textarea rows="2" cols="45" class="p-3" readonly disabled>{{result}}</textarea>
    <button ngxClipboard  cbContent="{{result}}"  class="btn btn-primary">copy to clipboard</button> 
  </w3tk-action> -->

<div class="cardmx-0 mb-1 alert-primary">
  <div class="card-header d-flex justify-content-between fw-bold">
    <div>Actions</div>
        <div>
            <button (click)="clear()" class="btn py-0 px-2"><fa-icon [icon]="faTrash"></fa-icon></button>
            <button (click)="play()" class="btn p-0"><fa-icon [icon]="faPlay" class="text-success"></fa-icon></button>
        </div>
  </div>
</div>
  
<div>
  <div *ngFor="let action of dataService.actions">
    <w3tk-action [action]="action">
      <ng-content></ng-content>
    </w3tk-action>
  </div>

</div>
