// src/src/app/tools/drainfunds/drainfunds.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from 'src/app/shared/services/data.service';
import { Web3Service } from 'src/app/shared/services/web3.service';

@Component({
  selector: 'w3tk-drainfunds',
  templateUrl: './drainfunds.component.html',
  styleUrls: ['./drainfunds.component.scss']
})
export class DrainfundsComponent implements OnInit {
  input: string = "";
  nrOfAddresses: number = 5;
  derivationPath: string = "m/44'/60'/0'/0/0";
  targetAddress: string = "";
  gas: number = 21000;
  gasPrice: number = 10;
  output: string = "";

  constructor(public dataService: DataService) { }

  ngOnInit(): void {
  }

  async drainFunds() {
    this.output = "";
    try {

      if(!Web3Service.isValidAddress(this.targetAddress)) {
        this.output = "Target address is invalid!";
        return;
      }
      console.log("drain funds started...");

      var phrases = this.input.split("\n").map(element => element.trim());

      phrases.forEach(line => {
        
        if(line.length < 2) { // can also be lower than 10, 2 is just what I chose
          return;
        }

        if(line.startsWith("0x")) {
          this.drain(line);
        }
        else {
          var keys = Web3Service.getPrivateKeys(line, this.nrOfAddresses, this.derivationPath);
          keys.forEach(async key => {
            await this.drain(key);
          });
        }

      });

    } catch (error) {
      this.output = String(error);
    }
    console.log("drain funds finished!");
  }

  async drain(key: string) {
    var tmpResult = await Web3Service.drainFunds(key, this.targetAddress, 
      this.dataService.network, this.gas, this.gasPrice);
    if(tmpResult.length > 0) {
      this.output += tmpResult + "\n";
    }
  }

}

<div class="card bg-dark">
    <h5 class="card-header bg-dark">Drain Funds</h5>
    <div class="card-body">
        <p class="card-text">
            Enter one or multiple seed phrases, a target address and execute this tool to move all
            funds of the addresses of the seed phrases to the target address.
        </p>

        <div class="card-text">
            <div class="row">
                <div class="col">
                    <textarea class="form-control font-code" rows="2" [(ngModel)]="seedPhrases"></textarea>
                </div>
            </div>

            <div class="row">
                <div class="col-6">
                    Number of derived addresses: <br />
                    <input type="number" class="form-control" max="100" min="1" [(ngModel)]="nrOfAddresses">
                </div>
                <div class="col-6">
                    Derivation path: <br />
                    <input type="text" class="form-control" [(ngModel)]="derivationPath">
                </div>
            </div>

            
            <div class="row">
                <div class="col">
                Target Address: <br />
                <input type="text" class="form-control" [(ngModel)]="targetAddress">
                </div>
            </div>

            <div class="row">
                <div class="col-6">Gas: <input type="number" class="form-control" [(ngModel)]="gas"></div>
                <div class="col-6">
                    Gas Price (Gwei): <input type="number" class="form-control" [(ngModel)]="gasPrice">
                </div>
            </div>
            <br />
        </div>
        <p class="card-text">
            <button (click)="drainFunds()" class="btn">Drain Funds</button>
        </p>
        <p class="card-text">
            <textarea class="form-control font-code" rows="20" disabled>{{output}}</textarea>
        </p>
    </div>
</div>

// src/app/tools/drainfunds/page.tsx
'use client';
import { useState } from 'react';
import { Web3Service } from '@/lib/services/web3.service';
import { useAppStore } from '@/lib/store';
import { Card, CardHeader, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';

export default function DrainFundsPage() {
  const network = useAppStore((s) => s.network);
  const [input, setInput] = useState('');
  const [nrOfAddresses, setNrOfAddresses] = useState(5);
  const [derivationPath, setDerivationPath] = useState("m/44'/60'/0'/0/0");
  const [targetAddress, setTargetAddress] = useState('');
  const [gas, setGas] = useState(21000);
  const [gasPrice, setGasPrice] = useState(10);
  const [output, setOutput] = useState('');

  const drain = async (key: string) => {
    const tmpResult = await Web3Service.drainFunds(key, targetAddress, network, gas, gasPrice);
    if (tmpResult.length > 0) {
      setOutput((prev) => prev + tmpResult + '\n');
    }
  };

  const drainFunds = async () => {
    setOutput('');
    try {
      if (!Web3Service.isValidAddress(targetAddress)) {
        setOutput('Target address is invalid!');
        return;
      }

      const phrases = input.split('\n').map((element) => element.trim());

      for (const line of phrases) {
        if (line.length < 2) continue;

        if (line.startsWith('0x')) {
          await drain(line);
        } else {
          const keys = Web3Service.getPrivateKeys(line, nrOfAddresses, derivationPath);
          for (const key of keys) {
            await drain(key);
          }
        }
      }
    } catch (error) {
      setOutput(String(error));
    }
  };

  return (
    <Card>
      <CardHeader><h5>Drain Funds</h5></CardHeader>
      <CardContent className="space-y-4">
        <p>
          Enter one or multiple seed phrases or private keys as well as a target address which will receive the funds.
          Press the &apos;Drain Funds&apos; button and all funds will be transfered from seed phrase/private key to the target address.
        </p>
        <Textarea className="font-code" rows={2} value={input} onChange={(e) => setInput(e.target.value)} />
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="text-sm">Number of derived addresses:</label>
            <Input type="number" max={100} min={1} value={nrOfAddresses} onChange={(e) => setNrOfAddresses(Number(e.target.value))} />
          </div>
          <div>
            <label className="text-sm">Derivation path:</label>
            <Input type="text" value={derivationPath} onChange={(e) => setDerivationPath(e.target.value)} />
          </div>
        </div>
        <div>
          <label className="text-sm">Target Address:</label>
          <Input type="text" value={targetAddress} onChange={(e) => setTargetAddress(e.target.value)} />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="text-sm">Gas:</label>
            <Input type="number" value={gas} onChange={(e) => setGas(Number(e.target.value))} />
          </div>
          <div>
            <label className="text-sm">Gas Price (Gwei):</label>
            <Input type="number" value={gasPrice} onChange={(e) => setGasPrice(Number(e.target.value))} />
          </div>
        </div>
        <Button onClick={drainFunds}>Drain Funds</Button>
        <Textarea className="font-code" rows={20} disabled value={output} />
      </CardContent>
    </Card>
  );
}
