// src/app/tools/genseedphrase/page.tsx
'use client';
import { useState } from 'react';
import { Web3Service } from '@/lib/services/web3.service';
import { Card, CardHeader, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';

export default function GenSeedPhrasePage() {
  const [nrOfSeeds, setNrOfSeeds] = useState(1);
  const [genSeeds, setGenSeeds] = useState('');

  const genSeedPhrase = () => {
    let result = '';
    for (let i = 0; i < nrOfSeeds; i++) {
      result += Web3Service.genSeedPhrase() + '\n';
    }
    setGenSeeds(result);
  };

  return (
    <Card>
      <CardHeader><h5>Generate Seed Phrase(s)</h5></CardHeader>
      <CardContent className="space-y-4">
        <p>Generate as much BIP-39 seed phrases as you want by clicking one button.</p>
        <div>
          <label className="text-sm">Number of seed phrases:</label>
          <Input type="number" max={100} min={1} value={nrOfSeeds} onChange={(e) => setNrOfSeeds(Number(e.target.value))} />
        </div>
        <Button onClick={genSeedPhrase}>Generate</Button>
        <Textarea className="font-code" rows={20} disabled value={genSeeds} />
      </CardContent>
    </Card>
  );
}

// src/src/app/tools/gen-seed-phrase/gen-seed-phrase.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Web3Service } from 'src/app/shared/services/web3.service';

@Component({
  selector: 'w3tk-gen-seed-phrase',
  templateUrl: './gen-seed-phrase.component.html',
  styleUrls: ['./gen-seed-phrase.component.scss']
})
export class GenSeedPhraseComponent implements OnInit {
  genSeeds: String = "";
  nrOfSeeds: Number = 1;

  constructor() { }

  ngOnInit(): void {
  }

  genSeedPhrase()
  {
    this.genSeeds = "";

    for(var i = 0; i < this.nrOfSeeds; i++) {
      this.genSeeds += Web3Service.genSeedPhrase() + "\n";
    }
  }

}

<div class="card bg-dark">
    <h5 class="card-header bg-dark">Generate Seed Phrase</h5>
    <div class="card-body">
      <p class="card-text">
          Generate as much BIP-39 seed phrases as you want by clicking one button.
      </p>
      <p class="card-text">
        Number of seed phrases: <br />
        <input type="number" class="form-control" max="100" min="1" [(ngModel)]="nrOfSeeds">
    </p>
    <p class="card-text">
      <button (click)="genSeedPhrase()" class="btn btn-primary" >Generate</button>
    </p>
    <p class="card-text">
        <textarea class="form-control font-code" rows="20" disabled>{{genSeeds}}</textarea>
        
       </p> 
    </div>
  </div>
