// _archive/angular-app/src/app/tools/tools-sidebar/tools-sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { faCode, faHammer, faKey, faLink, faWallet } from '@fortawesome/free-solid-svg-icons';
import { Action } from 'src/app/shared/actions/action';
import { Module } from 'src/app/shared/model/module';
import { DataService } from 'src/app/shared/services/data.service';
import { ToolsData } from '../tools.data';

@Component({
    selector: 'w3tk-tools-sidebar',
    templateUrl: './tools-sidebar.component.html',
    styleUrls: ['./tools-sidebar.component.scss'],
    standalone: false
})
export class ToolsSidebarComponent implements OnInit {

  faWallet = faWallet;
  faHammer = faHammer;
  faCode = faCode;
  faKey = faKey;
  faLink = faLink;

  tools = ToolsData.tools;
  
  constructor(public dataService: DataService) { }

  ngOnInit(): void {
  }

  addAction(action: Action) {
    this.dataService.addAction(action);
  }

}

<div class="px-3 pt-3 text-white h-100 d-flex flex-column">

    <div style="white-space: nowrap; text-align: center;">
      <a href="#" [routerLink]="['/tools']" class="link-light text-decoration-none">Tools</a>
    </div>
      <hr>

    <div class="accordion flex-grow-1" id="menuAccordion" style="overflow-y: auto;">

      <div *ngFor="let tool of tools; let i = index" class="accordion-item">
        <h2 class="accordion-header" id="{{ 'acc-heading-' + i }}">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" [attr.data-bs-target]="'#acc-collapse-' + i" aria-expanded="true" [attr.aria-controls]="'acc-collapse-' + i">
            <fa-icon [icon]="tool.icon" class="px-2"></fa-icon> {{tool.module}}
          </button>
        </h2>
        <div id="{{ 'acc-collapse-' + i }}" class="accordion-collapse collapse show" [attr.aria-labelledby]="'acc-heading-' + i">
          <div *ngFor="let action of tool.actions" class="accordion-body" title={{action.name}}>
            <button href="#" class="nav-link" [routerLink]="action.route">{{action.name}} <img *ngIf="action.requiresConnection" src="assets/img/circle.svg" class="p-2" title="This action requires an active internet connection." style="float: right;"></button> 
          </div>
        </div>
      </div>

    </div>
</div>

// src/components/ToolsSidebar.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ToolsData } from '@/lib/tools-data';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

export function ToolsSidebar() {
  const pathname = usePathname();
  const tools = ToolsData.tools;

  return (
    <div className="px-3 pt-3 text-foreground h-full flex flex-col">
      <div className="whitespace-nowrap text-center">
        <Link href="/tools" className="text-foreground no-underline">Tools</Link>
      </div>
      <hr className="border-border my-2" />
      <Accordion type="multiple" defaultValue={tools.map((t) => t.module)} className="grow overflow-y-auto">
        {tools.map((tool) => (
          <AccordionItem key={tool.module} value={tool.module}>
            <AccordionTrigger className="py-1 text-sm">
              <span className="flex items-center gap-2">
                <tool.icon className="h-4 w-4" /> {tool.module}
              </span>
            </AccordionTrigger>
            <AccordionContent>
              {tool.actions.map((action) => (
                <Link
                  key={action.route}
                  href={action.route}
                  className={`block w-full text-left py-1 pl-6 text-sm no-underline ${pathname === action.route ? 'text-accent' : 'text-foreground'} hover:text-accent`}
                  title={action.name}
                >
                  {action.name}
                  {action.requiresConnection && (
                    <img src="/img/circle.svg" className="p-2 float-right" title="This action requires an active internet connection." alt="requires connection" />
                  )}
                </Link>
              ))}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
}
